### ISSUE TITLE
BaseFormSet.__init__() got an unexpected keyword argument 'request'

### ISSUE THREAD

**Issue by abriemme** [unfoldadmin/django-unfold#1402]
**What version of Unfold are you using?**

After upgrading from 0.59 to 0.60

**What version of Django are you using?**

I'm using django 5.1.9

**What browser are you using?**

Brave latest

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

No

**Describe your issue**

After upgrading from 0.59 to 0.60,

```
Traceback (most recent call last):
  File ".venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1964, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/unfold/mixins/base_model_admin.py", line 42, in changeform_view
    return super().changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/unfold/mixins/action_model_admin.py", line 92, in changeform_view
    return super().changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1893, in _changeform_view
    formsets, inline_instances = self._create_formsets(
                                 
  File ".venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2338, in _create_formsets
    formset = FormSet(**formset_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/forms/models.py", line 1111, in __init__
    super().__init__(data, files, prefix=prefix, queryset=qs, **kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/django/forms/models.py", line 684, in __init__
    super().__init__(
    ^

Exception Type: TypeError
Exception Value: BaseFormSet.__init__() got an unexpected keyword argument 'request'
```

**Comment by lukasvinclav** [comment]
@abriemme how to reproduce the issue?

**Comment by dirkmoors** [comment]
+1

**Comment by lukasvinclav** [comment]
@dirkmoors the question is still same. How can I reproduce the issue? I believe the problem is related to the inline definition. Can I see it?

**Comment by Tonkonozhenko** [comment]
https://github.com/unfoldadmin/django-unfold/blob/fdfff986cbf532d747a5ceb0d6914b26f25b2fce/src/unfold/admin.py#L195
The request is coming here. I'll try to provide better reproduce steps a bit later

**Comment by pnost** [comment]
I also had to delete request and per page from kwargs for my EmailTemplateAdmin, that I use in django-post_office as I got the same error when I am trying to open the change-view

```
def get_formset_kwargs(self, request, obj, inline, prefix):
        kwargs = super().get_formset_kwargs(request, obj, inline, prefix)
        if "request" in kwargs:
            del kwargs["request"]
        if "per_page" in kwargs:
            del kwargs["per_page"]
        return kwargs
```

**Comment by lukasvinclav** [comment]
@pnost @dirkmoors @Tonkonozhenko @abriemme here I created quick fix. Can somebody do the testing if it works? To be honest, I still don't know how to reproduce the issue so I'm just guessing what could be wrong:

https://github.com/unfoldadmin/django-unfold/pull/1406

**Comment by Tonkonozhenko** [comment]
@lukasvinclav, for me it helped, no more error

**Comment by lukasvinclav** [comment]
@Tonkonozhenko ok, merged into `main`. I'm expecting release early next week.

**Comment by Tonkonozhenko** [comment]
Thanks! I'll use the version from GitHub to monitor how it works.

**Comment by bln-guardian** [comment]
Hey guys, in my case i needed to do:

```
class Unfold_ModelAdmin_fix(ModelAdmin):
    def get_formset_kwargs(
        self, request: HttpRequest, obj: Model, inline: InlineModelAdmin, prefix: str
    ) -> dict[str, any]:
        logger = getLogger(__name__)
        logger.warning("Request: %s, Object: %s, Inline: %s, Prefix: %s", request, obj, inline, prefix)

        formset_kwargs = super().get_formset_kwargs(request, obj, inline, prefix)
        formset_kwargs["request"] = request

        if not hasattr(inline, "per_page"):
            formset_kwargs.pop("request", None)

        return formset_kwargs
```

**Comment by frobert** [comment]
Same issue here...

**Comment by lukasvinclav** [comment]
@frobert how does your inline causing this issue looks like? If you can share the code and don't forget to attach imports.

**Comment by frobert** [comment]
@lukasvinclav nothing special..

imports:
from django.contrib.contenttypes.admin import GenericTabularInline
from unfold.admin import ModelAdmin, TabularInline
from comments.models import Comment

Inline
class CommentInline(GenericTabularInline, TabularInline):
    model = Comment
    extra = 1 
    readonly_fields = ('created_at',)
    tab = True

comments model is made using GenericForeignKey

as soon as i remove the "CommentInline" everything works ok .. Or if I downgrade to version "0.59.0" everything works ok.

-----

TypeError at /business_contacts/contact/1/change/
BaseFormSet.__init__() got an unexpected keyword argument 'request'
Request Method:	GET
Request URL:	http://localhost:8000/business_contacts/contact/1/change/
Django Version:	5.2.3
Exception Type:	TypeError
Exception Value:	
BaseFormSet.__init__() got an unexpected keyword argument 'request'
Exception Location:	/usr/local/lib/python3.13/site-packages/django/forms/models.py, line 684, in __init__
Raised during:	import_export.admin.change_view
Python Executable:	/usr/local/bin/python
Python Version:	3.13.5
Python Path:	
['/app',
 '/app',
 '/app',
 '/usr/local/lib/python313.zip',
 '/usr/local/lib/python3.13',
 '/usr/local/lib/python3.13/lib-dynload',
 '/usr/local/lib/python3.13/site-packages']
Server time:	Thu, 26 Jun 2025 13:29:17 +0200

**Comment by lukasvinclav** [comment]
@frobert `GenericTabularInline` needs to be imported from `unfold.admin`. Docs: https://unfoldadmin.com/docs/inlines/paginated/

Anyway, next week I will ship the fix provided above which should fix this problem in case of wrong import.

**Comment by frobert** [comment]
@lukasvinclav missed that one :/ It works now as expected. Thank you for your time.

**Comment by lukasvinclav** [comment]
I believe the issue is fixed now. If somebody has still the same problem, let me know.

**Comment by mazulo** [comment]
I started having this exact issue after I upgraded unfold from `0.59.0` to `0.63.0`. Here's my stacktrace:

```bash
TypeError: BaseFormSet.__init__() got an unexpected keyword argument 'request'
ERROR 2025-08-08 12:20:25,991 django.request: Internal Server Error: /admin/service_records/servicerecord/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1984, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/unfold/mixins/base_model_admin.py", line 42, in changeform_view
    return super().changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/unfold/mixins/action_model_admin.py", line 92, in changeform_view
    return super().changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
  File "/usr/local/lib/python3.13/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1840, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 1911, in _changeform_view
    formsets, inline_instances = self._create_formsets(
                                 ~~~~~~~~~~~~~~~~~~~~~^
        request, form.instance, change=False
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2364, in _create_formsets
    formset = FormSet(**formset_params)
  File "/usr/local/lib/python3.13/site-packages/django/forms/models.py", line 1111, in __init__
    super().__init__(data, files, prefix=prefix, queryset=qs, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/django/forms/models.py", line 684, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        **{
        ^^^
    ...<5 lines>...
        }
        ^
    )
    ^
TypeError: BaseFormSet.__init__() got an unexpected keyword argument 'request'
```

My django admin class looks like this:

```python
from django.contrib import messages
from django.db import models
from django.http import HttpRequest
from django.urls import path
from django.utils.translation import gettext_lazy as _
from import_export.admin import ExportActionModelAdmin
from unfold.admin import ModelAdmin, StackedInline, TabularInline
from unfold.contrib.filters.admin import AutocompleteSelectMultipleFilter
from unfold.decorators import display



class ServiceAdmin(ModelAdmin, ExportActionModelAdmin):
    change_form_template = "admin/service_records/change_form.html"
    resource_classes: ClassVar = [ServiceResource]
    list_filter_submit = True  # Submit button at the bottom of the filter
    inlines = (
        DriverInline,  # Uses the StackedInline
        LocationInline,  # Uses the TabularInline
    )
```

Does any of this ring a bell of what is happening?

-------
> UPDATE

I had to do the following to make it work again:

```python
def get_formset_kwargs(
    self,
    request: HttpRequest,
    obj: Model,
    inline: InlineModelAdmin[MyModel, MyOtherModel],
    prefix: str,
 ) -> dict[str, Any]:
    formset_kwargs = cast(
        dict[str, Any], super().get_formset_kwargs(request, obj, inline, prefix)
    )
    formset_kwargs.pop("request", None)
    formset_kwargs.pop("per_page", None)

    return formset_kwargs
```

**Comment by lukasvinclav** [comment]
@mazulo if you think, you have found a regression, please create new ticket

**Comment by aviyadeveloper** [comment]
Please do not fix the issue by popping the `request` and `per_page`  `kwargs`, as you will be hindering functionality.

When using unfold ModelAdmin the two kwargs are added automatically when a `per_page` prop is given to the inline. 

```python
 class ModelAdmin:
    # ...
    def get_formset_kwargs(
        self, request: HttpRequest, obj: Model, inline: InlineModelAdmin, prefix: str
    ) -> dict[str, Any]:
        formset_kwargs = super().get_formset_kwargs(request, obj, inline, prefix)

        if hasattr(inline, "per_page"):
            formset_kwargs["request"] = request
            formset_kwargs["per_page"] = inline.per_page

        return formset_kwargs
```


This works well out of the box. Because all of the provided inlines utilize a special class that handle these kwargs:

```python
class TabularInline(BaseInlineMixin, BaseModelAdminMixin, BaseTabularInline):
    formset = PaginationInlineFormSet


class StackedInline(BaseInlineMixin, BaseModelAdminMixin, BaseStackedInline):
    formset = PaginationInlineFormSet


class GenericStackedInline(
    BaseInlineMixin, BaseModelAdminMixin, BaseGenericStackedInline
):
    formset = PaginationGenericInlineFormSet


class GenericTabularInline(
    BaseInlineMixin, BaseModelAdminMixin, BaseGenericTabularInline
):
    formset = PaginationGenericInlineFormSet
```


The problem arises when you provided a customized FormSet. When you do that you have to  make sure that it inherits from one of the relevant classes above.

```python
from unfold.forms import PaginationInlineFormSet

class JustAnotherFormSet(PaginationInlineFormSet):
    # ...
```

and not from the default django forms:
```python
from django.forms import BaseInlineFormSet`

class BrokenFormSet(BaseInlineFormSet):
    # ...
```

So this isn't a bug or an issue in the software. Could be improved in the docs perhaps if people stumble upon this regularly.

**Comment by abriemme** [comment]
I was using a custom FormSet and the solution of @aviyadeveloper fixed my issues.
